<<<<<<< HEAD
# jsxSingleQuote: true
=======
jsxSingleQuote: true
>>>>>>> 9df27f5e69400c3b074ed780b4d784a6e5f15bac
# semi: false
printWidth: 120
proseWrap: never
singleQuote: true
htmlWhitespaceSensitivity: 'css'
endOfLine: 'lf'
